<a href="https://colab.research.google.com/github/thatguyandy27/Pytorch-Tutorials/blob/main/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [3]:
x_ones =  torch.ones_like(x_data) # shape & datatype
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # dtype override
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7537, 0.8091],
        [0.0350, 0.5718]]) 



In [4]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeors Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7254, 0.0249, 0.6269],
        [0.1055, 0.3095, 0.5925]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeors Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [5]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [7]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

print(f"Device of tensor: {tensor.device}")

True
Device of tensor: cuda:0


In [8]:
#slicing

tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"last column: {tensor[..., -1]}")
# sets the idex 1 column of every row to 0
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# join tensors using torch.stack & torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
# arithmetic operations

# matrix multiplication
y1 = tensor @ tensor.T

y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1: {y1} \n")
print(f"y2: {y2} \n")
print(f"y3: {y3} \n")


# element wize product multiplication
z1 = tensor * tensor

z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f"z1: {z1} \n")
print(f"z2: {z2} \n")
print(f"z3: {z3} \n")



y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [13]:
# single element tensors:
agg = tensor.sum()
agg_item = agg.item()
print(f"Item: {agg_item}")
print(f"Type: {type(agg_item)}")
print(f"Sum: {agg}")
print(f"Sum(type): {type(sum)}")


Item: 12.0
Type: <class 'float'>
Sum: 12.0
Sum(type): <class 'builtin_function_or_method'>


In [14]:
# in place operators end with _

# In-place operations save some memory,
# but can be problematic when computing derivatives because of an immediate
# loss of history. Hence, their use is discouraged.

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [15]:
# Numpy
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
# changing the tensor changes the numpy!
t.add_(t)
print(f"t: {t}")
print(f"n: {n}")
# changing the numpy changes the tensor!
n += 10
print(f"t: {t}")
print(f"n: {n}")

t: tensor([4., 4., 4., 4., 4.])
n: [4. 4. 4. 4. 4.]
t: tensor([14., 14., 14., 14., 14.])
n: [14. 14. 14. 14. 14.]
